from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("verify/<str:token>", views.verify, name="verify"),
    path("settings", views.settings_view, name="settings"),
    path("product/<int:product_id>", views.product, name="product"),
    path("category", views.category, name="category"),
    path("category_products/<str:category_name>",
         views.category_products, name="category_products"),
    path("pendings", views.pending_page, name="pendings"),
    path("inprogess", views.inprogress_page, name="inprogress"),
    path("new_order/<int:product_id>", views.new_order, name="new_order"),
    path("order/<int:order_id>", views.order_page, name="order_page"),
    path("search_products", views.search_products, name="search_products"),
    path("my_orders", views.my_orders, name="my_orders"),
    path("manage_orders", views.manage_orders, name="manage_orders"),
    path("manage_orders/<int:order_id>",
         views.order_details, name="order_details"),
    path("create_order", views.create_order, name="create_order"),
    path("create_order/details/<str:product_title>",
         views.create_order_details, name="create_order_details"),
    path("manage_products", views.manage_products, name="manage_products"),
    path("create_product", views.create_product, name="create_product"),
    path("edit_product/<int:product_id>",
         views.edit_product, name="edit_product"),
    # API routes
    path("settings/edit", views.edit_settings, name="edit-settings"),
    path("order/<int:order_id>/refresh",
         views.refresh_order, name="refresh_order"),
    path("delete_cus_order",
         views.delete_cus_order, name="delete_cus_order"),
    path("save_edit_cus_order", views.save_edit_cus_order,
         name="save_edit_cus_order"),
    path("delete_purchase_order", views.delete_purchase_order,
         name="delete_purchase_order"),
    path("save_edit_p_order", views.save_edit_p_order, name="save_edit_p_order"),
    path("delete_product", views.delete_product, name="delete_product"),
    path("upload_image", views.upload_image, name="upload_image"),
    path("delete_image", views.delete_image, name="delete_image"),
    path("product/<int:product_id>/active",
         views.active_product, name="active_product"),
    path("category/type/<str:type_select>", views.update_sub_categories,
         name="update_sub_categories"),
    path("create_order/category_select",
         views.category_select, name="category_select")
]
