# Generated by Django 4.1.2 on 2023-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchases",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(upload_to="esb/static/esb"),
        ),
    ]
