# Generated by Django 4.1.2 on 2023-02-10 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0002_purchases_date_time_alter_product_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["active", "title"]},
        ),
        migrations.AlterField(
            model_name="purchases",
            name="buyer",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="esb.category",
            ),
        ),
    ]
