# Generated by Django 4.1.2 on 2023-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0004_alter_category_options_alter_purchases_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title", "type"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="purchases",
            options={"verbose_name_plural": "Purchases"},
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
