# Generated by Django 4.1.2 on 2023-02-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0007_remove_purchases_date_time_purchases_due_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
