# Generated by Django 4.1.2 on 2023-02-10 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0009_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchases",
            name="buyer",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
