# Generated by Django 4.1.2 on 2023-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0012_alter_purchases_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchases",
            name="buyer",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to="esb.customer"
            ),
        ),
    ]
