# Generated by Django 4.1.2 on 2023-02-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0014_alter_purchases_buyer_delete_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchases",
            old_name="due_date_time",
            new_name="date_time",
        ),
    ]
