# Generated by Django 4.1.2 on 2023-02-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0017_customerpurchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchases",
            name="buyer",
        ),
    ]
