# Generated by Django 4.1.2 on 2023-03-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0022_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_product",
                to="esb.product",
            ),
        ),
    ]
