# Generated by Django 4.1.2 on 2023-03-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0024_alter_product_options_remove_product_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="index",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
