# Generated by Django 4.1.2 on 2023-03-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0025_alter_productimage_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["product__id", "index"]},
        ),
    ]
