# Generated by Django 4.1.2 on 2023-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esb", "0027_alter_productimage_options_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(default="default", max_length=32),
            preserve_default=False,
        ),
    ]
